# local 환경
spring:
  profiles:
    group:
      "local": "common,localdev"

---
spring:
  config:
    activate:
      on-profile: common
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect

## for jstl
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp

---
spring:
  config:
    activate:
      on-profile: localdev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;mode=MYSQL
    username: sa
    password: 1234
  sql:
    init:
      mode: always
      data-locations: classpath:data-h2.sql

## 운영 환경
#---
#spring.profiles: set1
#spring.profiles.include: H2
##spring.profiles.include: real-db
#
#server:
#  port: 8081
#
#---
#spring.profiles: set2
#spring.profiles.include: H2
##spring.profiles.include: real-db
#
#server:
#  port: 8082
#  port: 8082